language: python
cache:
  pip: true
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - npm
before_install:
- pip install awscli --upgrade
install: cd spa; npm install; cd ..
script: make build
deploy:
- provider: script
  script: make deploy-dev-travis
  skip_cleanup: true
  on:
    branch: serverless
env:
  global:
  - secure: J/7ANWBBJ1mmJOIg97/IXVIwArsFV/exHyLqxeujy8VHQSzMoI9LalSgExknDnj5k9J9ZPZHPL0t5AShqHN4wpNTUu3suz7JG0eZZerJbAobEK6WJx/wLaMCORXVD20paqiUP3otlhF236w85hYgSK6dA37pvSN/YJpYCwbsvdbN7O440r1Y8LeLoh/KMXZaIFqz3dk6CdidB02QKVRcB2opoxYiS0oE2ATWy8+YDqpcWTiYMSZt1lAYSSiquIw70BnUnu9taiS4OCZXn3j806s9UK0GAyskO0xAmAnFzAgshpvNPz6mQPZuwxKssnWULmH2KJxOmjLiz0rSv+LSg2FyuY3JesMJYFF39Iaqukr3DINfXY4C4G3+qc1OKAG1auJTylvRrKDxqaqerSYOepU9uosd7x0s9L7fdQdgERo7HUNm3tVudNIERr2vZZLcfRamHjZ68EpLYKr51WiVZBEI2ye0ZRqR/off7U+TqwQaaI1sFQD65BugM8OJ3w3Gl7UU6qho6eU3+7jyjpwssJM6KiHrWyfO5JazBHdpZM2E1qX5MqonvwIWazqtQ+o2O0Z9pc7RvkVF3FYlvE19LbH8ZbVYUPBGm9fsOav+M3gNq/eP2X/J0kmyHJn7vdPQL6Usc6OSEsA+L6FUXLlsqlrcFTRph8WxPQASJ3W0Iiw=
  - secure: U+hYCtKIq4i2duHqIPG/BLvMJd5FFxljyWzhfE/9bUMqc7eRxNlaB2RWgvTy7LSKCprQUWoDOPBhUqhf+x48lATJqQG6sqhM+QBXHf/s7tR8mx0T68SeKoabmw9aV6YDKEfSgh6kvmm9mxtOWg82zzUWuoS80VkL0Kum5wDk7OKi4kPbRuhrdcDmPVRugnxUpw5X8c4m6Clccm7nbuOl3nxzI+jfbgI5Y56c2L3Ysed9ckMcRK/VCh7CJ8xG9V0cTNkBUF9TfX+mHxteYryui2E2iDPs/R333/bI3RvzK48S8Jna7CdFgtyWL/aVDsXmXAv+DvbVYAhNMinUMFpLFtzvKxLX846wZOMQfeXrohmv336knGJ+3XDe6l/2pwm6vKPNSzQsB6pO/sYbSYjFSxWAlRNiComEMqEwqm0qGYwKdCf7nfDV7nBXiozqE/KteO/tryzWXKzAvNczWn/Eifn6fjcuKoMuySTMaJW+6/TtMKnfHOUACxwWtBJXmEYCLSCZzj/ikHr4OJmB2K/6zkqGr2XSHaDdryeXlm2smgQwwj51UwjaBOM3N0JXymOid0gYPXnMVehNby+9nhJHHmAhSeRC9gnH3Z8uSTZG1QISlzAoz55BYO5Fbp6H3vK9fOtg6IhCsL+Es1iuJjPItDbHzl+0plXE9eTo+nXOXF8=
